### ISSUE TITLE
(help) How do I migrate database from matt-FFFFFF's PostgreSQL to alexbelgium's Postgres, both in HA addons. 

### ISSUE THREAD

**Issue by wyx087** [lildude/ha-addon-teslamate#35]
Hi lildude, 

Thanks for taking up the mantle with this Teslamate addon. 

Please can you help me migrate from matt-FFFFFF's PostgreSQL 12.5 addon to alexbelgium's Postgres 15 addon? 

The docker compose command in Teslamate documentation doesn't map into Home Assistant addon. What other way is there to do this database migration?  Could alex's Portainer addon help here? 

Sorry, I've only used HA addons. Docker commands is completely out of my depth. 

Thanks very much

**Comment by lildude** [comment]
The process is pretty much what is documented in the [TeslaMate docs](https://docs.teslamate.org/docs/maintenance/backup_restore) with a few tweaks to use `docker exec [POSTGRES CONTAINER ID]` instead of `docker compose`.

Your question has motivated me to finally make the switch. I’ll try find some time this weekend and I’ll document my steps.

**Comment by wyx087** [comment]
Thanks for reply. But how do I run docker exec commands in Home Assistant OS? 

Use an SSH add on? But they are sandboxed from each other isn’t it? Need host level access, somehow?

**Comment by lhomann** [comment]
> Hi lildude,
> 
> Thanks for taking up the mantle with this Teslamate addon.
> 
> Please can you help me migrate from matt-FFFFFF's PostgreSQL 12.5 addon to alexbelgium's Postgres 15 addon?
> 
> The docker compose command in Teslamate documentation doesn't map into Home Assistant addon. What other way is there to do this database migration? Could alex's Portainer addon help here?
> 
> Sorry, I've only used HA addons. Docker commands is completely out of my depth.
> 
> Thanks very much

I did a migration a few weeks back. Out of memory did I do those steps:
1 Install Add-on "pgAdmin4" from https://github.com/expaso/hassos-addons
2 Start the add on and open the web UI
3 Make two connections, 1 to your old postgres and the other to the new postgres
4 create new database with same name as the old database on the new postgres instanc
5 create a new postgres user with same username and password on the new postgres DB.
6 now make a backup of the old DB
7 now restore. select the new database and right click and select "restore"
8 stop old postgres database
9 reconfig teslamate with paramaters to use the new postgress hostname (username and pwd should be the same, because you have created it in step 5)
10 start teslamate

good luck

**Comment by wyx087** [comment]
Awesome, that worked. Thank you very much for your help. 

Needed some juggling because both PpostgreSQL addons used the same port and pgAdmin wouldn't connect to a different port for me. 

0. Should have old PostgreSQL 12.5 and Teslamate addon. Also installed [new Postgres 15 as per ReadMe requirements](https://github.com/lildude/ha-addon-teslamate?tab=readme-ov-file#requirements) and this TeslaMate addon
1. Install Add-on "pgAdmin4" from https://github.com/expaso/hassos-addons
2. Start the pgAdmin4 add on and open the UI
3. Make a connection to old (host name, user and password copy from old TeslaMate config page) 
4. Back up the database specified in old TeslaMate config page. 
5. Stop old old TeslaMate addon and PostgreSQL 12.5 addon. 
6. In new Postgres 15 addon config, input database name that was just backed up. User and password is same as step 3. 
7. Start new Postgres 15 addon. 
8. Restart pgAdmin4 addon 
9. Restore database from earlier backup that was done in Step 4. 
10. Config new TeslaMate as per [migration notes of this addon](https://github.com/lildude/ha-addon-teslamate?tab=readme-ov-file#migrating-to-this-version-of-the-add-on), take care to change to new database_host "db21ed7f-postgres". 

Everything seems to work so far. Yet to take a drive but it's fetching data as expected, when car is woken up. 

Thanks very much for keeping this great addon going.
